#!/bin/bash

#Script is used for calculation of magnetic structures

change_atoms="$(head -n 1 CRYSTAL.d12 | awk '{print $2}')"

cat fort2.34 | awk -v change_atoms=$change_atoms '{ if ($1 == "2") {$1 = change_atoms}; print }'
